---
# Some common variables used in more then one roles
 
nextcloud_credential_store:    "secrets" # Store the secrets on the ansible command server in this repo
nextcloud_data_dir:            "{{ nextcloud_base_dir }}/data"
nextcloud_www_dir:             "{{ nextcloud_base_dir }}/www"
nextcloud_config_dir:          "{{ nextcloud_base_dir }}/config"
nextcloud_database_dir:        "{{ nextcloud_base_dir }}/database"
nextcloud_database_dump_dir:   "{{ nextcloud_base_dir }}/database-dump"


traefik_config_dir:            "{{ nextcloud_base_dir }}/traefik"

portainer_data_dir:            "portainer-data-vol"

nextcloud_container_data_dir:  /var/nc-data

docker_postgres_image:         10-alpine
docker_mysql_image:            latest
docker_nextcloud_image:        fpm-alpine
docker_nginx_image:            alpine
docker_adminer_image:          latest
docker_traefik_image:          alpine
docker_watchtower_image:       latest
docker_redis_image:            4-alpine
docker_collabora_image:        latest
docker_turnserver_image:       latest

docker_occ_cmd:                'docker exec --user www-data nextcloud php occ'

# dns resolver (nginx reverse ip lookup) set to 127.0.0.1
# see http://blog.zorinaq.com/nginx-resolver-vulns/
nginx_resolver: '127.0.0.1'

# use rclone to backup to a cloud storage, see https://rclone.org for more details
# `set_modtime` is necessary since the remote dir is ntfs, and modtime can't be set
restic_repo:     "rclone:backup-nextcloud:/mnt/external_drive/backups/nextcloud_backup"
rclone_remote: |
      [backup-nextcloud]
      type = sftp
      host = rabenimmermehr.hopto.org
      user = ansible
      port = 2222
      key_file = /home/rabefabi/.ssh/id_rsa
      set_modtime = false 